name: python-update-manual.yml
on:
  push:
    branches: [ master ]
    paths:
      - cfbs/args.py
  pull_request:
    branches: [ master ]
    paths:
      - cfbs/args.py
jobs:
  diff-detecton:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python: 3.9
      - name: Install cfbs
        run: pip3 install .
      - name: Install dependencies
        run: pip3 install argparse-manpage
      - name: run the man generator
        run: python cfbs/man_generator.py
      - name: see if there are any changes
        run: |
          git diff --exit-code || touch git_diff_exists
          if [ -f git_diff_exists ]; then echo "Changes need to be commited"; else echo "No changes to commit"; fi
      - name: Commit new MAN file
        if: hashFiles('git_diff_exists') !=  ''
        run: |
          git config user.name 'GitHub'
          git config user.email '<noreply@github.com>'
          git add cfbs/cfbs.1
      - name: Create Pull Request
        if: hashFiles('git_diff_exists') != ''
        uses: cfengine/create-pull-request@v6
        with:
          commit-message: 'updates to man page'
          base: 'master'
          title: MAN page updated due to changes in interface
          body: ''
          reviewers: |
            olehermanse
            nickanderson
          branch: updating/man
